---
title: "USCOTS2023 Workshop"
---

## USCOTS 2023 Workshop Schedule

[SCORE Network website](https://scorenetwork.org/){target="_blank"}

* 830  	Welcome and Introductions

* 845 	Score Network Overview  

* 915 	Example SCORE modules

  Module [Triathlon Correlations](https://isle.stat.cmu.edu/SCORE/ironman_triathlon/){target="_blank"}

  Module [Unbreakable Records Baseball](https://isle.stat.cmu.edu/SCORE/Unbreakable_Records_Baseball_Hits/){target="_blank"}

  Module [Marathon Records](https://isle.stat.cmu.edu/SCORE/Marathons_SCORE_Template/){target="_blank"}
  
  Module [Hockey Regression](https://isle.stat.cmu.edu/SCORE/NHLShots/){target="_blank"}
  
  Module [Stolen Bases](https://isle.stat.cmu.edu/SCORE/stolen-bases-module/){target="_blank"}


* 1000  _Coffee Break_

* 1030 	Module Planning

* 1045  Module Content Creation 

  [Module Author Handbook](https://drive.google.com/file/d/1bCYSqy1sr-ppDtOJno9XdWho38QfcFl8/view?usp=share_link){target="_blank"}

* 1100  Sports Data and Modules in Progress

* 1115  Module Brainstorming

* 1200  _Lunch provided_

* 1300  Discussion Modules

* 1330  Module Submission Process
  
  [Module Submission Form](https://docs.google.com/forms/d/e/1FAIpQLScvIGzM_Q66D1XHApMPY8Cfq3TRCT7MfQsbg6rUM8sO8jKNeg/viewform){target="_blank"}

* 1400  Review of Modules
  
  [Pedagogical Review Form ](https://forms.gle/yFux4dEkUQstSMfa7){target="_blank"}
  
  Module [PGA Putt for Dough ](https://isle.stat.cmu.edu/SCORE/PGA_drive_putt){target="_blank"}
  
  Module [Lacrosse PLL v. NLL](https://isle.stat.cmu.edu/SCORE/lacrosse_nll_vs_pll){target="_blank"}
  
  Module [League of Legends, Buffing and Nerfing](https://isle.stat.cmu.edu/SCORE/league_of_legends/){target="_blank"}

  Module [Softball Join and Merge](https://isle.stat.cmu.edu/SCORE/softball_merging_tables/){target="_blank"}


* 1430  _Coffee Break_

* 1500  Discussion of Review Process

* 1530  Module Work Time

* 1600  Script and Video discussion

* 1620  Wrap-Up and Evaluation



